
image:
  repository: gcr.io/heden-enterprises/he-nginx
  tag: latest


# how many pods for the deployment?
# default is 2
# replicaCount: 2


# your gcp external ip name
# you can create one with:
#
# $ gcloud compute addresses create web-external-ip --global --network-tier=PREMIUM
#
# default is web-external-ip
# externalIPName: web-external-ip


# override your kubernetes resource names if you so desire
# otherwise they default to the chart's release name
# names:
#   deployment: heden-enterprises-web
#   service: heden-enterprises-web
#   ingress: heden-enterprises-web
