apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "heden-enterprises-web.ingress-name" . }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ include "heden-enterprises-web.externalIPName" . }}
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: letsencrypt-production
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: tls-cert
    hosts:
    - hedenenterprises.io
  loadBalancerIp: 130.211.19.206
  rules:
    - host: hedenenterprises.io
      http:
        port: 80
        paths:
        - backend:
            serviceName: {{ include "heden-enterprises-web.service-name" . }}
            servicePort: 80
    # - host: hedenenterprises.io
    #   http:
    #     port: 80
    #     paths:
    #     - path: /.*
    #       backend:
    #         serviceName: {{ include "heden-enterprises-web.service-name" . }}
    #         servicePort: 80